### ISSUE TITLE
feat: 장소 스크랩 기능 구현 (search place 페이지)

### ISSUE THREAD

**Issue by yoojinjangjang** [Lets-Travel-Well/Lets-Travel-Well-Servlet#33]
### 🗄️ 종류

issue 종류를 선택하세요

- [x] New Feature

## 🔍Description

> 장소찾기 페이지에서 내가 원하는 장소를 스크랩 할 수 있는 기능 제공

## 📝Todo

- [ ] 검색한 장소들 중 마음에 드는 장소를 선택하여 스크랩시 내 장소로 등록하기
- [ ] 스크랩된 장소 중 취소를 할 경우 내 장소에서 제거 되기
- [ ] 장소 찾기 지도의 마커 표시와 팝업창 디자인 변경하기
    - [ ] 스크랩된 장소와 그렇지 않은 장소의 마커 다르게 표시하기
    - [x] 팝업창 디자인을 hover 방식이 아닌 click,close 방식으로 변경하기 
- [ ] my_travel 페이지 제작
    - [ ] 스크랩한 장소 리스트로 보여주기 
    - [ ] 스크랩한 장소 리스트에서 삭제하기 
    - [ ] 스크랩한 장소 중 최단 경로를 구할 장소 선택하기
